import Head from 'next/head'
import Script from 'next/script'
import Form from '../components/form'
import styles from '../styles/Home.module.css'

export default function Home() {

  let submitForm = async e => {
    e.preventDefault();

    hive_keychain.requestCustomJson(
      null, // account
      'custom_json_test', // tx category
      'Posting', // Posting or Active key
      JSON.stringify({tx_text: e.target['tx_text'].value}), // json
      "test msg", // display message
      function (response) {
        console.log("main js response - custom JSON");
        console.log(response);
      });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="favicon.ico"/>
      </Head>
      <main className={styles.main}>
        <Form onSubmit={submitForm}/>
      </main>
    </div>
  )
}
